### ISSUE TITLE
Mejorar panel administrativo de entradas

### ISSUE THREAD

**Issue by sdelquin** [pythoncanarias/web#111]
- Añadir email como primer campo para que sirva de href
- Quitar keycode y artículo de campos a mostrar
- Añadir un campo custom booleano que indique si se envió correo
- Añadir búsqueda por email, nombre, apellidos, keycode
- Añadir filtro por artículo
- Ordenar por el campo "sold_at" (más nuevos más arriba)

**Comment by euribates** [comment]
Fixed on branch hotfix#1
