### ISSUE TITLE
Crear un admin-action para generar las acreditaciones

### ISSUE THREAD

**Issue by sdelquin** [pythoncanarias/web#123]
- Sería deseable disponer de un `admin-action` para el modelo `Ticket` que permita generar las acreditaciones.
- La acreditación debería contener (al menos):
    - Logotipo de Python Canarias.
    - Nombre de evento.
    - Tipo de entrada.
    - Nombre y apellidos del asistente.
    - Número de la entrada.
- La acreditación debería tener un tamaño de 90x60mm

**Comment by Rulox** [comment]
Quitaría lo de "tipo de entrada", en realidad no nos aporta nada de información no?

**Comment by sdelquin** [comment]
No es especialmente relevante, pero tampoco "abulta" demasiado. Sería algo como:
`Normal/24`
`Early/7`
...
(el número que sigo al tipo no es el número de entrada dentro de ese tipo, sino el número de entrada de todo el evento)

**Comment by Rulox** [comment]
No lo veo útil

**Comment by sdelquin** [comment]
Sin problema. Como lo veas mejor 👍🏻

**Comment by euribates** [comment]
Ahora mismo no es util, pero para otros eventos si podr;ia serlo. Si no molesta mucho yo lo dejar;ia

**Comment by Syrka** [comment]
Creoq eu no hay necesidad de hacer esas diferencias. Ya que al final los vas a tratar igual. No es que haya una entrada premium con la que les damos cerveza de verdad. :joy:
