### ISSUE TITLE
Quizás no sea bueno recordar que se van a mandar las entradas al correo en un formulario donde no se pide el email

### ISSUE THREAD

**Issue by aplatanado** [pythoncanarias/web#124]
https://pythoncanarias.es/events/ticket/purchase/1/

**Comment by aplatanado** [comment]
Sí. Pero me han comentado que genera confusión decir que se mandará por
correo pero que no se pida en ese mismo formulario.
Uno se pregunta ¿y no lo piden?

**Comment by euribates** [comment]
ok, gracias por el aviso. Esta arreglado ya y se modifica el mensaje para indicar que el correo
se pedirá en el momento del pago. Cuando se desplieguen los cambios hoy o mañana ya debería estar.
