### ISSUE TITLE
Crear un admin-action para generación y envío de certificados de asistencia

### ISSUE THREAD

**Issue by sdelquin** [pythoncanarias/web#155]

**Comment by sdelquin** [comment]
Estaría bien que los certificados se generaran en MEDIA_ROOT/certificates para que pudieran ser accesibles desde una URL (tipo validación de documento electrónica) e incluir esta URL en el propio certificado.

**Comment by euribates** [comment]
Pero habria que resolver primero el problema de la firma, no?

**Comment by sdelquin** [comment]
Efectivamente. Queda eso pendiente también!

**Comment by sdelquin** [comment]
Los certificados de asistencia se firman con firma digital tanto por parte del presidente como del secretario de la asociación. Está acción es manual y no se quiere automatizar.
