### ISSUE TITLE
Página para publicar ofertas de empleo

### ISSUE THREAD

**Issue by sdelquin** [pythoncanarias/web#188]
Sería bueno disponer de un formulario en el que aquellas empresas interesadas en difundir ofertas de empleo relacionadas con Python, pudieran publicar sus condiciones.
Esta oferta luego pasaría a "revisión manual" y se publicaría en alguna URL de la web.

**Comment by euribates** [comment]
Sugerencia inicial de campos:

- Nombre de la empresa
- URL de la empresa
- Descripcion de la plaza
- URL para mas detalles
- Perfil ofertado
- Sueldo o rango salarial
- Fecha de creacion de la oferta
- Fecha de baja (por defecto, tres meses despues del alta o algo asi)
- Presencial / Remoto / Mixto

**Comment by sdelquin** [comment]
Fixed by #292
