### ISSUE TITLE
El perfil de ponente debería estar asociado a un evento

### ISSUE THREAD

**Issue by jdevera** [pythoncanarias/web#210]
Aunque hay algunos elementos de un ponente que puede que no cambien, como su nombre y datos de contacto, hay otros, sobre todo los visibles en la sección de un evento, que deberían ser específicos de un evento.

Por ejemplo, un mismo ponente que participa en dos eventos debería poder tener una foto de perfil o una bio diferente para cada evento.

**Comment by sdelquin** [comment]
El diseño de la base de datos actual lo permite. Se pueden crear tantas versiones de un ponente como se quieran, y vincular la versión que se quiera al evento correspondiente. No se ha hecho por simplicidad del montaje de los eventos.
