### ISSUE TITLE
Añadir la opción de ubicación virtual para eventos

### ISSUE THREAD

**Issue by sdelquin** [pythoncanarias/web#296]
Hasta ahora siempre hemos hecho eventos presenciales, con una ubicación física que incluía dirección postal y latitud/longitud. Hemos empezado a organizar eventos virtuales que se retransmiten en directo. Habría que preparar la base de datos para contemplar esta coyuntura.

**Comment by euribates** [comment]
Bastaria con poner el campo localizacion como Nullable?

**Comment by sdelquin** [comment]
Supongo que eso es parte de la solución. Para hacerlo bien también habría que añadir campo(s) para guardar el enlace de la videoconferencia. Por ejemplo, en este caso teníamos la URL de Youtube y la URL de Zoom Webinars.
