### ISSUE TITLE
Mejora IA bot Deckard (Véase Iniciativa Skynet)

### ISSUE THREAD

**Issue by euribates** [pythoncanarias/web#391]
Aprovechando la tabla de citas, mejorar a Deckard para que si alguien usa dos palabras de alguna de las citas almacenadas, suelte la  cita cual morcilla en el chat.

**Comment by jdevera** [comment]
Esto no pertenece más al repo de Deckard?

**Comment by sdelquin** [comment]
Migrada a https://github.com/pythoncanarias/pydeckard/issues/28
